title: "ELEANOR Travel"
email: "contact@eleanor-travel.com"   # Mets ton email pro si tu veux
description: "Agence de voyages haut de gamme - Le Kef, Tunisie"
baseurl: ""                           # racine du dépôt
url: "https://elabidka.github.io"     # pas d'espace, pas d'accents

# Thème
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

locale: fr
markdown: kramdown
highlighter: rouge

# Paramètres de navigation
header_pages:
  - index.md
  - about.md
  # tu pourras ajouter services.md plus tard

# Réseaux sociaux (optionnel)
author:
  name: "ELEANOR Travel"
  links:
    - label: "Facebook"
      url: "https://www.facebook.com/eleanor-travel"
    - label: "Instagram"
      url: "https://www.instagram.com/eleanor-travel"
